// Copyright © 2026 Zenin Easa Panthakkalakath

// Assembles out/webShell/ -- the phase-3 "minimal shell" of docs/proposals/webEdition.md: a
// statically servable copy of the desktop renderer running against src/renderer/webShims/*
// instead of src/preload.mjs's Electron IPC bridge. Requires npm run build:web to have already
// produced out/engineWeb/. See docs/developmentSetup.md's "Web build (experimental)" section.

import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { cp, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { pathExists, rootDirectory } from './developmentEnvironment.mjs';

const srcDirectory = join(rootDirectory, 'src');
const outputDirectory = join(rootDirectory, 'out', 'webShell');
const engineWebDirectory = join(rootDirectory, 'out', 'engineWeb');

if (!await pathExists(join(engineWebDirectory, 'konjugateEngine.js'))) {
    throw new Error('The web engine is not built. Run npm run build:web first.');
}

await rm(outputDirectory, { recursive: true, force: true });
await mkdir(outputDirectory, { recursive: true });

// Walks renderer.mjs's (and webShims/*.mjs's) own relative-import graph -- covers static
// imports, dynamic import(), and specifically the `new Worker(new URL(specifier,
// import.meta.url))` pattern webEngineLiveShim.mjs uses to locate its Worker module (NOT every
// `new URL(..., import.meta.url)` -- webShims/engine.mjs also uses that construction for the
// WASM engine's .js/.wasm asset URL, which is not an ES module and must not be walked as one) --
// so every .mjs file actually needed gets copied automatically instead of hand-listed and
// risking drift as those imports change.
const importPattern = /(?:from\s+|import\()\s*['"](\.[^'"]+)['"]|new\s+Worker\(\s*new URL\(\s*['"](\.[^'"]+)['"]/g;
const visitedModules = new Set();
async function walk(absolutePath) {
    if (visitedModules.has(absolutePath)) return;
    visitedModules.add(absolutePath);
    const content = await readFile(absolutePath, 'utf8');
    for (const match of content.matchAll(importPattern)) {
        await walk(join(dirname(absolutePath), match[1] ?? match[2]));
    }
}
await walk(join(srcDirectory, 'renderer', 'renderer.mjs'));
for (const shimFile of await readdir(join(srcDirectory, 'renderer', 'webShims'))) {
    await walk(join(srcDirectory, 'renderer', 'webShims', shimFile));
}
for (const absolutePath of visitedModules) {
    const destination = join(outputDirectory, relative(srcDirectory, absolutePath));
    await mkdir(dirname(destination), { recursive: true });
    await cp(absolutePath, destination);
}
// webShims/ is small and fully controlled by this build -- copy it wholesale too, so
// protobufjsMinimalShim.mjs (referenced only from index.html's importmap, not from any .mjs
// import statement) is never missed by the graph walk above.
await cp(join(srcDirectory, 'renderer', 'webShims'), join(outputDirectory, 'renderer', 'webShims'), { recursive: true });
await cp(join(srcDirectory, 'renderer', 'styles.css'), join(outputDirectory, 'renderer', 'styles.css'));

const packageJson = JSON.parse(await readFile(join(rootDirectory, 'package.json'), 'utf8'));
await writeFile(join(outputDirectory, 'renderer', 'webShims', 'buildInfo.mjs'),
    '/* Copyright © 2026 Zenin Easa Panthakkalakath */\n\n' +
    '// Generated by scripts/buildWebShell.mjs -- see src/renderer/webShims/buildInfo.mjs for the source placeholder.\n' +
    `export const version = ${JSON.stringify(packageJson.version)};\n`);

// index.html: insert protobufjs's classic script + importmap entry (see
// webShims/protobufjsMinimalShim.mjs for why) and the shim bootstrap's module script before
// renderer.mjs's, then uniformly reduce every "../../" path by one level -- this output tree has
// no src/ wrapper the way src/renderer/ does, so everything the source file reaches via "two
// levels up to the repo root" is one level up from here instead.
let html = await readFile(join(srcDirectory, 'renderer', 'index.html'), 'utf8');
html = html.replace('<html lang="en">', '<html lang="en" data-web-edition>');
html = html.replace(
    '<script src="../../node_modules/occt-import-js/dist/occt-import-js.js"></script>',
    '<script src="../../node_modules/protobufjs/dist/minimal/protobuf.min.js"></script>\n' +
    '    <script src="../../node_modules/occt-import-js/dist/occt-import-js.js"></script>'
);
html = html.replace(
    '"@cortex-js/compute-engine": "../../node_modules/@cortex-js/compute-engine/dist/esm-min/compute-engine.js"',
    '"@cortex-js/compute-engine": "../../node_modules/@cortex-js/compute-engine/dist/esm-min/compute-engine.js",\n' +
    '                "protobufjs/minimal.js": "./webShims/protobufjsMinimalShim.mjs"'
);
html = html.replace(
    '<script type="module" src="renderer.mjs"></script>',
    '<script type="module" src="webShims/index.mjs"></script>\n' +
    '    <script type="module" src="renderer.mjs"></script>'
);
html = html.replaceAll('../../', '../');
if (!html.includes('webShims/index.mjs') || !html.includes('data-web-edition') || !html.includes('protobufjsMinimalShim')) {
    throw new Error('index.html transform failed -- src/renderer/index.html may have changed shape since this script was written.');
}

// The CSP's sha256 hash covers the importmap <script>'s exact inline content (byte-for-byte,
// browser-CSP-hash semantics) -- adding the protobufjs/minimal.js entry above changed those
// bytes, so the original hash (computed for the desktop's unmodified importmap) no longer
// matches and the importmap gets silently blocked. Recompute it against what's actually served.
const importmapMatch = html.match(/<script type="importmap">([\s\S]*?)<\/script>/);
if (!importmapMatch) throw new Error('Could not locate the importmap script to rehash for CSP.');
const importmapHash = createHash('sha256').update(importmapMatch[1], 'utf8').digest('base64');
const cspMatch = html.match(/'sha256-[^']+'/);
if (!cspMatch) throw new Error('Could not locate the CSP script-src hash to replace.');
html = html.replace(cspMatch[0], `'sha256-${importmapHash}'`);
await writeFile(join(outputDirectory, 'renderer', 'index.html'), html);

await mkdir(join(outputDirectory, 'engine'), { recursive: true });
await cp(join(engineWebDirectory, 'konjugateEngine.js'), join(outputDirectory, 'engine', 'konjugateEngine.js'));
await cp(join(engineWebDirectory, 'konjugateEngine.wasm'), join(outputDirectory, 'engine', 'konjugateEngine.wasm'));

// Assets referenced directly by index.html's body (toolbar icons), plus the shape and component
// libraries webShims/misc.mjs fetches from.
await cp(join(rootDirectory, 'assets'), join(outputDirectory, 'assets'), { recursive: true });

// Examples: copy the raw files, then generate the directory listing a browser can't produce
// itself -- mirrors src/main.mjs's projectListExamples handler, for the bundled case.
const examplesDirectory = join(rootDirectory, 'examples');
await cp(examplesDirectory, join(outputDirectory, 'examples'), { recursive: true });
const exampleFiles = (await readdir(examplesDirectory)).filter((name) => name.endsWith('.kjt'));
const examplesManifest = new Map(JSON.parse(await readFile(join(examplesDirectory, 'manifest.json'), 'utf8'))
    .examples.map((entry) => [entry.id, entry]));
function exampleLabel(fileName) {
    const stem = fileName.replace(/\.kjt$/, '');
    return `${stem.charAt(0).toUpperCase()}${stem.slice(1)}`.replace(/([a-z0-9])([A-Z])/g, '$1 $2');
}
async function exampleDescription(stem) {
    const markdown = await readFile(join(examplesDirectory, `${stem}.md`), 'utf8').catch(() => '');
    const match = markdown.match(/## Overview\r?\n\r?\n([\s\S]+?)(?=\r?\n##\s|\r?\n*$)/);
    return match ? match[1].trim() : '';
}
const exampleEntries = await Promise.all(exampleFiles.map(async (fileName) => {
    const stem = fileName.replace(/\.kjt$/, '');
    return {
        id: fileName,
        label: exampleLabel(fileName),
        suggestedFilename: fileName,
        domains: examplesManifest.get(stem)?.domains ?? [],
        description: await exampleDescription(stem),
        thumbnailUrl: existsSync(join(examplesDirectory, `${stem}.png`)) ? `${stem}.png` : null
    };
}));
await writeFile(join(outputDirectory, 'examples', 'webManifest.json'), JSON.stringify(exampleEntries));

// Component library: same directory-listing problem as examples, for the bundled templates only
// (src/main.mjs's discoverComponentLibrary() also merges in a userData directory and installed
// plugins -- both dropped here, same as webShims/misc.mjs's componentLibrary.list() already
// documents).
const componentLibraryDirectory = join(rootDirectory, 'assets', 'componentLibrary');
const componentEntries = [];
for (const name of await readdir(componentLibraryDirectory)) {
    if (!name.endsWith('.json')) continue;
    try {
        componentEntries.push(JSON.parse(await readFile(join(componentLibraryDirectory, name), 'utf8')));
    } catch (error) {
        console.warn(`Skipping component template ${name}: ${error.message}`);
    }
}
await writeFile(join(outputDirectory, 'assets', 'componentLibrary', 'webManifest.json'), JSON.stringify(componentEntries));

await mkdir(join(outputDirectory, 'docs'), { recursive: true });
await cp(join(rootDirectory, 'docs', 'causalInferenceInteractionHelp.md'), join(outputDirectory, 'docs', 'causalInferenceInteractionHelp.md'));

// Python provider SDK (docs/proposals/webEdition.md, phase 4) -- fetched at runtime by
// src/webPythonProviderBridge.mjs and written into Pyodide's own virtual FS. Only the SDK
// package itself ships; nothing here depends on the native engine/sdk/python/ layout beyond it.
await cp(
    join(rootDirectory, 'engine', 'sdk', 'python', 'konjugate'),
    join(outputDirectory, 'pythonProviderSdk', 'konjugate'),
    { recursive: true, filter: (source) => !source.endsWith('__pycache__') }
);

const vendoredPackages = [
    'three', 'mathlive', join('@cortex-js', 'compute-engine'), 'occt-import-js', 'plotly.js-dist-min', 'protobufjs', 'pyodide'
];
for (const packageName of vendoredPackages) {
    await cp(join(rootDirectory, 'node_modules', packageName), join(outputDirectory, 'node_modules', packageName), { recursive: true });
}

console.log(`Web shell assembled at ${outputDirectory}.`);
