// Copyright © 2026 Zenin Easa Panthakkalakath

// Regenerates distribution/homebrew/konjugate.rb from a real published GitHub release, computing
// actual sha256 hashes against the real DMG assets instead of hand-maintaining values in git that
// go stale the moment the next release ships -- confirmed the hard way: the first hand-written
// draft was already wrong (still labeled v0.7.3) by the time v0.7.4 shipped.
//
// Two flavors, one template:
//   - default: the cask for the *first* Homebrew/homebrew-cask submission (see below). Official casks
//     may not paper over missing signing, so it only tells the user how to clear macOS's quarantine.
//   - `--tap`: the cask for Konjugate's own tap (zenineasa/homebrew-konjugate, see
//     docs/packageManagerDistribution.md). A personal tap isn't held to the official repo's rules, so
//     this one clears the quarantine flag itself in a postflight step, which is what lets
//     `brew install --cask` hand over an app that opens without the Gatekeeper "damaged" warning.
//     Written to distribution/homebrew/tap/Casks/konjugate.rb, the layout a tap repository needs.
//
// The default flavor only ever matters for the *first* Homebrew/homebrew-cask submission (see
// docs/packageManagerDistribution.md) -- every update after that PR merges flows through
// eugenesvk/action-homebrew-bump-cask against the live upstream tap, not this file, so it only
// needs to be accurate at the moment someone is about to submit it. That's why it's regenerated
// on demand rather than kept committed: a committed copy would just go stale again.

import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { rootDirectory } from './developmentEnvironment.mjs';

const repo = 'zenineasa/Konjugate';
const arguments_ = process.argv.slice(2);
const forTap = arguments_.includes('--tap');
const requestedTag = arguments_.find((argument) => !argument.startsWith('--'));
const releaseUrl = requestedTag
    ? `https://api.github.com/repos/${repo}/releases/tags/${requestedTag}`
    : `https://api.github.com/repos/${repo}/releases/latest`;

const releaseResponse = await fetch(releaseUrl, { headers: { Accept: 'application/vnd.github+json' } });
if (!releaseResponse.ok) {
    throw new Error(`Could not fetch release metadata from ${releaseUrl}: ${releaseResponse.status} ${releaseResponse.statusText}`);
}
const release = await releaseResponse.json();
const version = release.tag_name.replace(/^v/, '');

async function sha256ForAsset(assetName) {
    const asset = release.assets.find((candidate) => candidate.name === assetName);
    if (!asset) throw new Error(`Release ${release.tag_name} has no ${assetName} asset.`);
    const assetResponse = await fetch(asset.browser_download_url);
    if (!assetResponse.ok) throw new Error(`Could not download ${assetName}: ${assetResponse.status} ${assetResponse.statusText}`);
    const bytes = Buffer.from(await assetResponse.arrayBuffer());
    return createHash('sha256').update(bytes).digest('hex');
}

// Only x64 Linux exists today -- release.yml's build matrix only runs Linux on ubuntu-22.04
// (x64), no arm64 Linux runner -- so, unlike the macOS side, the Linux artifact isn't
// arch-conditional. depends_on arch: :x86_64 below (scoped inside on_linux, not top-level, so it
// doesn't also restrict macOS) stops this from being offered to an arm64 Linux user it can't run on.
const [armSha256, intelSha256, linuxSha256] = await Promise.all([
    sha256ForAsset(`Konjugate-${version}-arm64.dmg`),
    sha256ForAsset(`Konjugate-${version}-x64.dmg`),
    sha256ForAsset(`Konjugate-${version}-x86_64.AppImage`)
]);

const header = forTap
    ? `# Homebrew Cask for Konjugate's own tap (zenineasa/homebrew-konjugate) -- generated by
# scripts/generateHomebrewCask.mjs --tap from release ${release.tag_name}, and committed to the tap
# repository by release.yml's homebrewTapRelease job. Don't edit it by hand: the next release
# overwrites it.`
    : `# Homebrew Cask for Konjugate -- generated by scripts/generateHomebrewCask.mjs from release
# ${release.tag_name}. NOT submitted anywhere yet: copy this into a fork of Homebrew/homebrew-cask
# at Casks/k/konjugate.rb and open a PR there (see docs/packageManagerDistribution.md). Only
# needed for the very first submission -- eugenesvk/action-homebrew-bump-cask handles every
# update after that PR merges, against the live upstream tap, not this file.`;

// What happens about macOS's quarantine flag differs by flavor -- see the header comment.
const macosLaunchSupport = forTap
    ? `    # Homebrew marks everything it installs as downloaded-from-the-internet, and an app that is
    # neither signed nor notarized then fails Gatekeeper's check with "Konjugate is damaged". This
    # clears that mark, which is what makes a plain \`brew install --cask\` give an app that opens.
    postflight do
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{appdir}/Konjugate.app"]
    end

    caveats <<~EOS
      Konjugate is not code-signed or notarized yet (an active choice while the project is in
      beta). To let it open, this cask removes macOS's quarantine flag from Konjugate.app after
      installing it -- which also means macOS has not checked the app. Only install it if you
      trust this tap and the project.
    EOS
`
    : `    caveats <<~EOS
      Konjugate is not code-signed or notarized yet (an active choice while the project is in
      beta). If macOS reports that "Konjugate.app is damaged and can't be opened", run:
        xattr -cr "#{appdir}/Konjugate.app"
    EOS
`;

const cask = `${header}
#
# Covers both macOS (DMG/.app) and Linux (AppImage, via the app_image artifact stanza) in one
# cask, following the same on_macos/on_linux pattern real casks like cursor.rb and warp.rb use --
# Homebrew Cask has real, current Linux support, not just macOS, confirmed against those live casks.

cask "konjugate" do
  arch arm: "arm64", intel: "x64"

  version "${version}"
  sha256 arm:   "${armSha256}",
         intel: "${intelSha256}",
         x86_64_linux: "${linuxSha256}"

  on_macos do
    url "https://github.com/${repo}/releases/download/v#{version}/Konjugate-#{version}-#{arch}.dmg",
        verified: "github.com/${repo}/"
    depends_on macos: :big_sur

    app "Konjugate.app"

${macosLaunchSupport}
    zap trash: [
      "~/Library/Application Support/Konjugate",
      "~/Library/Preferences/com.konjugate.plist",
      "~/Library/Saved Application State/com.konjugate.savedState",
    ]
  end

  on_linux do
    url "https://github.com/${repo}/releases/download/v#{version}/Konjugate-#{version}-x86_64.AppImage",
        verified: "github.com/${repo}/"
    depends_on arch: :x86_64

    app_image "Konjugate-${version}-x86_64.AppImage", target: "Konjugate.AppImage"
  end

  name "Konjugate"
  desc "Graph-native simulation engine for engineering and digital twins"
  homepage "https://github.com/${repo}"

  livecheck do
    url :url
    strategy :github_latest
  end
end
`;

// A tap repository keeps its casks in a Casks/ directory at its root.
const outputDirectory = forTap ? join(rootDirectory, 'distribution', 'homebrew', 'tap', 'Casks') : join(rootDirectory, 'distribution', 'homebrew');
const outputPath = join(outputDirectory, 'konjugate.rb');
await mkdir(outputDirectory, { recursive: true });
await writeFile(outputPath, cask);
console.log(`Generated ${outputPath} for ${release.tag_name} (arm64 sha256 ${armSha256}, x64 sha256 ${intelSha256}, linux x64 sha256 ${linuxSha256}).`);
